import './globals.css';
import Navbar from './components/navbar'; // Pastikan path ini benar

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Navbar tetap terlihat di semua halaman */}
        <Navbar />
        {/* Main container untuk konten halaman */}
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
